# Modify these 3 parameters, rename to secrets.yaml and ecrypt using Ansible Vault.
ansible_user: admin
ansible_password: 'Vau1t_ftw!'

# Enable Password (If needed)
ansible_become_password: 'En@ble_pass!'